chenxiaolong/avbroot

avbroot/boot.py
Magisk commit ad0e6511e11ebec65aa9b5b916e1397342850319 stopped embedding stub.apk into magiskinit, so we need to ensure it is extracted and available to boot_patch.sh.
=> avbroot/boot.py: Add support for separate stub.apk

README.md
=> README.md: Clarify that only Linux is supported

README.md
* Clarify boot image partitions. It is no longer the case that only `boot` and `vendor_boot` are patched.
* Describe how to check if an OTA file is A/B.
* Remove mentions of signapk now that avbroot signs zips itself.
* Minor grammar changes.
=> README.md: Improve documentation

avbroot.py
=> Add unused return object when extracting

avbroot.py
There are no interdependencies across different boot images, so run the patches in parallel. It only saves a few seconds, but it's a free optimization.
=> avbroot.py: Run boot image patches in parallel

avbroot.py
This helps guard against future directory structure changes. So far, this has remained the same across Magisk versions 22 through 25.2.
The check can be overridden with `--ignore-magisk-version`.
Issue: #37
=> avbroot.py: Validate Magisk apk version

avbroot/ota.py
This fixes an issue where `BrokenPipeError` was being raised while handling a `KeyboardInterrupt` on Linux. This was happening because `^C` and `^\` cause `SIGINT`/`SIGQUIT` to be sent to the entire process group, including `openssl cms`. openssl would die and `ZipFile`'s `__exit__` would try to finalize the zip during stack unwinding, causing a write to a dead pipe.
=> avbroot/ota.py: Fix EPIPE when interrupted by controlling TTY

tests/distros/Containerfile.arch, tests/distros/Containerfile.arch-wine, tests/distros/wine/pacman.additional.conf, tests/distros/wine/python3.sh, tests/tests_containerized.py
Yes, this is installing msys2 packages directory on the Arch Linux root filesystem. Yes, it works!
=> tests: Add new image for running tests for Windows in Wine

README.md, avbroot/boot.py, avbroot/main.py, tests/tests.py
This is useful for folks who want to apply the Magisk root patch themselves via the Magisk app or use KernelSU. When `--prepatched` is used, avbroot will skip the root patch, but still apply the otacerts patch.
To help protect against accidental use of the wrong boot image, avbroot will only accept a prepatched image if all the header fields and section types match the original image. The only exception is the number of ramdisks, which is allowed to increase (Magisk may create a ramdisk in an image that didn't originally have one).
=> Add support for using prepatched boot images

avbroot/main.py, avbroot/ota.py
Due to zipfile's internal locking (no pread support), the actual I/O isn't parallelized. However, this still speeds up `extract --all` very significantly because the extraction process is mostly CPU bound by decompression.
=> Extract images from payload in parallel

avbroot/boot.py
This ensures that the user isn't replacing the kernel image with another one that's not binary compatible (based on the GKI kernel module interface version).
=> avbroot/boot.py: Check KMI version when using prepatched image

.github/workflows/ci.yml
Also run workflows on pull requests from forks. It would be useful to check if code from external contributors is checked before it gets merged instead of after.
=> Run workflow on pull requests

README.md
=> README.md: Improve project description and remove suggestion for compiling AOSP from source

.github/workflows/modules.yml, README.md
=> Add GitHub Actions workflow to build modules

avbroot/src/format/avb.rs
AVB 2.0 mandates that the header is 64 KiB or less, so enforce this both when parsing and when writing vbmeta headers. Hash trees and FEC data are also read into memory, so enforce limits corresponding to a 4 GiB partition image.
Since these limits are so small, this lets us remove nearly all checked integer conversions since a direct cast will never result in truncation.
Issue: #157
=> avb: Enforce size limits to prevent DoS

avbroot/src/format/bootimage.rs
The kernel, ramdisk(s), second stage bootloader, and device tree components are limited to 64 MiB. In practice, no device has boot partitions larger than 64 MiB, so this limit should never be hit. The vendor v4 bootconfig component is limited to 1 KiB, which is about ~25x the size of the Pixel 7 Pro's bootconfig.
Issue: #157
=> bootimage: Enforce size limits to prevent DoS

avbroot/src/format/bootimage.rs
=> bootimage: Fix potential divide-by-0 and multiplication overflow

avbroot/src/format/cpio.rs
This prevents avbroot from being killed for excessive memory usage due to the entry header specifying a very large file name or file size (larger than what's actually contained in the file).
This threshold for switching to incremental reallocation is 1 KiB for file names and 1 MiB for file data.
Issue: #157
=> cpio: Read data by incremental reallocation after a threshold

avbroot/src/format/fec.rs
This also limits the block size to 16384. There are currently no known images that use anything larger than 4096.
Issue: #157
=> fec: Ensure FEC data size and grid size won't overflow

.github/workflows/ci.yml
=> ci.yml: Only cancel previous runs for pull requests

avbroot/src/cli/ota.rs
There are a ton of options and simply displaying them in a giant list is not very readable.
=> Group `ota patch --help` options into sections

avbroot/src/cli/ota.rs
avbroot currently has a check to ensure that AVB signature verification isn't completely disabled by non-zero vbmeta header flags. This is done to ensure that the user isn't given a false sense of security when the OS is built in an insecure way. This commit makes a few changes better reject insecure OTAs.
The first change is extending the non-zero flags check to all vbmeta images. Previously, only vbmeta images that needed to be updated as a result of patching/re-signing were checked.
The second change is ensuring that there are no critical partitions present in `payload.bin`, but missing from the vbmeta descriptors. For example, if the vbmeta descriptor for `system.img` is missing, the patching process will fail with a fatal error that cannot be bypassed.
Unfortunately, it's not …
=> Add more checks to ensure AVB is actually providing security

README.md
During the migration to avbroot 2.0, these options have been renamed. Reflect this in the Readme.
=> Update README.md to use new options

avbroot/src/cli/ota.rs, avbroot/src/format/avb.rs
=> cli/ota: Improve error reporting when descriptor types are mismatched

README.md
* Split out requirements from the warnings/caveats section and move it to the top. Hopefully this helps new users determine whether they can even use avbroot quicker.
* Split usage section into separate usage, initial install, and updates sections. This should hopefully make the steps much easier to follow without a bunch of steps being prefixed with `[Initial setup only]`.
* Explicitly state what arguments are required for Magisk, KernelSU, and unrooted setups instead of directing users to the advanced usage section.
* Don't assume that everyone will use Magisk in the other sections.
* Explicitly state the assumption that the device should already running the OS build that the user wants to patch during initial install.
* Add step to updates section for installing an updated Magisk or …
=> README.md: Make sections easier to follow

avbroot/src/format/compression.rs
`lineage-20.0-20231109-nightly-taimen-signed.zip` is an example of an OTA that uses XZ-compressed ramdisks.
Issue: #203
=> compression: Add support for XZ-compressed ramdisks

avbroot/src/cli/ota.rs
Some devices use the legacy Android/ChromiumOS-specific `dm=` kernel command line option to configure dm-verity without userspace helpers. These options are specified in kernel command line descriptors in the system partition's vbmeta header, which need to be merged into the parent vbmeta image for the bootloader to see them.
This commit adds support for merging property descriptors and kernel command line descriptors. Property descriptors are merged based on an exact string match of the property key. Kernel command line descriptors are merged based on the (non-empty) text before the first equal sign.
Issue: #203
=> cli/ota: Merge property and kernel cmdline descriptors from child into parent

avbroot/src/cli/ota.rs
Previously, when running `avbroot ota verify`, only the payload chunk hashes were verified.
=> cli/ota: Also verify whole-partition hashes

avbroot/src/format/hashtree.rs
With the dm-verity hash tree format, each digest is salted, meaning it first hashes the salt byte string and then the actual data. Previously, the salt was being rehashed for each digest operation. Instead, the salted SHA-256 context can be computed once and then cloned when needed.
The performance improvement is pretty minor, but it's worth doing anyway since it's not any more complex.
=> hashtree: Precompute salted SHA-256 context

README.md
These helped me when installing GrapheneOS. Not 100% sure if the additional reboot is necessary on all OSes.
Thank you for your fantastic work, @chenxiaolong!
BTW: I created a script that automatically provides patched OTAs via GitHub pages based on avbroot and custota: https://github.com/schnatterer/rooted-graphene/
=> README: Add minor clarifications

.github/workflows/ci.yml
=> ci.yml: Build universal binary for macOS

README.md
OnePlus seems to be getting worse and worse with some devices not being recoverable.
Issue: #290
=> README.md: Strongly discourage using any device besides Google Pixels

avbroot/src/patch/boot.rs
There is nothing new that isn't already supported.
=> Add support for Magisk 28000

avbroot/src/format/ota.rs
While patched OTAs produced by avbroot always include the protobuf version of the OTA metadata, the original OTA may not. Verifying those with `avbroot ota verify` is a valid use case.
Issue: #366
=> format/ota: Allow verifying OTAs without metadata.pb

README.md
avbroot will not support patching these internal OTAs because it requires modifying filesystems and creating incremental OTAs. However, it should be possible to do this manually if someone really wants to try out a 16K page size kernel.
=> Add documentation for Android 16's developer switch for 16K page size kernels

avbroot/src/util.rs
This makes the type potentially more useful outside of just our current use case of just error messages. Ranges where the starting value is exclusive are no longer supported, but weren't used anyway.
=> util: Wrap std's range types instead of inventing our own

avbroot/src/format/lp.rs
AOSP says that for non-empty images, the first 4 KiB block is supposed to be filled with zeros to prevent it from being interpreted as an old BIOS boot sector. The previous implementation relied on that to distinguish between empty and non-empty images. However, Samsung decided to use this region for their own `SignerVer02` structure, so the heuristic doesn't work.
AOSP's liblp tries to parse the input file as an empty image before falling back to parsing as a normal image. We'll do the same.
=> lp: Stop checking for zeroed first block

avbroot/src/format/lp.rs
There are two documented behaviors in liblp that are violated with the on-disk super partition layout after a virtual A/B CoW merge:
1. The partition name includes a `-` due to the `-cow` suffix. This is not meant to be a valid character.
2. The extent list is likely to have many gaps and not be sorted. The format documentation says that gaps are not allowed.
This commit updates avbroot's LP parser to be less strict so that it can load real on-device super partitions. The extent allocator for the `pack` subcommand remains unchanged though, so avbroot will always produce LP images with sorted, gapless extents.
=> format/lp: Relax validation checks to parse on-device super partition

avbroot/src/cli/ota.rs
* Try to avoid fail-fast behavior to show as many errors as possible. Parsing errors always fail immediately, but verification errors don't.
* Move the recovery `otacerts.zip` check to the end to let more important checks run first.
* Improve error message when `otacerts.zip` does not contain the signing certificate for the OTA to make it clear the issue is not that the zip contains no certificates at all.
* Always run the recovery `otacerts.zip` check, but just log the error as a warning when running with `--skip-recovery-ota-cert`.
* Fix unformatted error context string when parsing a boot image's `otacerts.zip` file fails.
Discussion: #426
=> cli/ota: Improve `ota verify` otacerts.zip handling

avbroot/src/cli/ota.rs, avbroot/src/format/ota.rs
This way, we can fail hard for parsing errors, but not for verification errors in `avbroot ota verify`.
=> format/ota: Decouple OTA signature parsing from verification

Cargo.lock, avbroot/src/cli/avb.rs, avbroot/src/cli/cpio.rs, avbroot/src/cli/ota.rs, avbroot/src/crypto.rs, avbroot/src/format/avb.rs, avbroot/src/format/bootimage.rs, avbroot/src/format/sparse.rs, avbroot/src/patch/boot.rs, avbroot/src/patch/otacert.rs, avbroot/src/util.rs
=> Update dependencies and fix clippy lints
