chenxiaolong/avbroot

README.md, avbroot.py, avbroot/boot.py
* Apply OTA certificate patch to the boot image if no `vendor_boot` image exists.
* Only manually decompress ramdisk cpio archives if the boot image header version is 4. `magiskboot` automatically decompresses older header versions.
Fixes: #5
=> Add support for older Pixel devices

avbroot/vbmeta.py
This is the same as commit 163540b2b68a0aa0123c413ed776be9405f65571, except for the vbmeta image. Some older devices' vbmeta images were originally signed by an RSA 4096 key.
Fixes: #9
=> avbroot/vbmeta.py: Force signing algorithm from SHA256_RSA2048 to SHA256_RSA4096

avbroot.py
Using /dev/shm breaks compatibility with non-Linux operating systems. On Linux, most distros mount /tmp as a tmpfs anyway.
Fixes: #15
=> avbroot.py: Decrypt keys to standard temp directory

avbroot.py
Systems where `/tmp` is on a tmpfs and have less free RAM may have trouble with the patching process.
=> avbroot.py: Use the output directory as the default temporary directory path

avbroot/util.py
`os.uname` is only available on Unix. `os.name == "posix"` also wouldn't work because Cygwin emulates a Posix environment. `sys.platform` should probably work.
Should fix #20
=> Use sys.platform to determine if system is Linux

avbroot.py, avbroot/util.py
If any standard temp directory environment variables are set, then don't use the output directory as the temp directory.
Issue: #22
=> Respect standard TMPDIR/TEMP/TMP environment variables

avbroot/external.py, avbroot/ota.py
There are two noteworthy changes:
1. https://android.googlesource.com/platform/build/+/bf01f8b3f0ce70047840999d95a449bf03b407c6%5E%21/
This reduces the number of fields that we have to apply the hacky common.OPTIONS override for.
2. https://android.googlesource.com/platform/build/+/8895f9eceac4ad568bcca724c4dcf8faf5b865f4%5E%21/
This removes the dependency on the host having the zip command installed.
=> Update external submodules

avbroot.py, avbroot/util.py
Now that avbroot no longer needs to create huge temp files, just use the OS's default temp directory.
=> Stop setting default temporary directory to the output directory

avbroot/util.py
This hasn't broken anything in the past because the Pixel OTA payloads haven't been using ZERO or DISCARD blocks.
=> avbroot/util.py: Fix variable name typo in zero_n()

avbroot.py, avbroot/boot.py, avbroot/ota.py
Only OxygenOS 12 and 13 can work because older builds use the legacy metadata file instead of the newer protobuf format.
Differences from Pixel devices:
* There's a `recovery` image. It contains `otacerts.zip` instead of `vendor_boot` or `boot`. The image uses a version 4 `ANDROID!` header, not `VNDRBOOT`.
* The `payload.bin` uses `ZERO` blocks with no sha256 checksum.
=> Add support for OnePlus OTAs

avbroot.py, avbroot/boot.py, avbroot/openssl.py, avbroot/ota.py, avbroot/util.py, avbroot/vbmeta.py
openssl supports passing the passphrase via a file descriptor, so let's do that and avoid ever putting plaintext private keys on the filesystem, even if it is a tmpfs.
=> Pass encrypted private keys to openssl directly

README.md, avbroot.py, avbroot/boot.py, avbroot/formats/bootimage.py, avbroot/formats/compression.py, avbroot/formats/cpio.py, avbroot/formats/padding.py, avbroot/openssl.py, avbroot/util.py
This commit reimplements the magiskboot patching process natively in Python. By doing so, avbroot gains cross platform support and there's no longer a need to execute an Android binary on a non-Android Linux system, which had pitfalls that already had to be worked around.
Boot images and cpio archives are handled by new custom parsers added to avbroot. Legacy lz4 compression is done by a wrapper around the python lz4 library (a new dependency). Gzip compression is handled natively by python. Other compression methods and OEM-specific boot image formats are not supported because devices that use the modern Android A/B OTA scheme do not use those.
Output files are still bit-for-bit reproducible across runs, but they are different from what prior avbroot commits produced:
* avbroot's cpio …
=> Remove dependency on magiskboot

avbroot/ota.py, avbroot/vbmeta.py
The mechanism is still the same (modifies global state), but the code is a bit cleaner.
=> Use unittest.mock.patch for replacing classes and variables

avbroot/boot.py, avbroot/formats/cpio.py
On bluejay, the boot image does not contain a ramdisk. In this scenario, magiskboot creates a new lz4_legacy-compressed ramdisk, so we'll do the same.
This commit also changes the .backup/ directory structure generation so that it is done dynamically.
Fixes: #42
=> avbroot/boot.py: Construct Magisk ramdisk from scratch if no ramdisk exists

avbroot/formats/compression.py
For v2 boot images that use gzip headers, the current system time was begin added to the gzip header while recompressing the ramdisk, which broke reproducibility. This commit hardcodes the timestamp to 0 (unix epoch time).
=> avbroot/formats/compression.py: Hardcode timestamp in gzip header

avbroot/formats/bootimage.py, avbroot/formats/cpio.py, avbroot/util.py, extra/README.md, extra/bootimagetool.py, extra/cpiotool.py, tests/tests.conf
This PR adds a couple of new tools for working with boot images and cpio archives on the command line. They're just small wrappers around avbroot's `avbroot.formats.*` libraries. They're useful for dissecting and comparing boot images when troubleshooting.
=> Add new bootimagetool and cpiotool utilities

tests/README.md, tests/distros/Containerfile.alpine, tests/distros/Containerfile.arch, tests/distros/Containerfile.debian, tests/distros/Containerfile.fedora, tests/distros/Containerfile.opensuse, tests/distros/Containerfile.ubuntu, tests/distros/Containerfile.ubuntu-lts, tests/tests.py, tests/tests_containerized.py
The officially supported distros are now Alpine, Arch, Debian, Fedora, Fedora, OpenSUSE, and Ubuntu. The new script will build images for these distros and concurrently run `tests.py` inside containers.
=> tests: Add infrastructure for running tests in podman

README.md, avbroot/formats/bootimage.py, avbroot/formats/compression.py
This is needed for Debian 11 compatibility.
Fixes: #50
=> Add support for Python 3.9

avbroot/ota.py, avbroot/util.py
This fixes temporary output files sometimes not being cleaned up and openssl cms sometimes not being killed when the user interrupts the process.
=> Fix skipped cleanup logic caused by fixing bare except lint warnings

avbroot/boot.py
Otherwise, the "version made by" field in the central directory (2 bytes immediately after CD magic) are `\x14\x00` on Windows and `\x14\x03` everywhere else.
=> avbroot/boot.py: Mark otacerts.zip entries as created on Unix

avbroot/util.py
This fixes temporary files being left behind when interrupted on Windows.
=> avbroot/util.py: open_output_file: Close file before unlinking on Windows

README.md, avbroot/main.py, avbroot/vbmeta.py
Some Android builds ship with a root vbmeta image with flags that disable AVB completely. This commit adds a new check for these flags so that the patching process will fail and also adds a new `--clear-vbmeta-flags` option for forcibly setting the flags to 0.
Issue: #60
=> Add option to clear vbmeta flags

avbroot/main.py
Not really needed for normal usage, but nice to have a way to extract everything without needing other tools.
=> avbroot/main.py: Add --all option for extract subcommand

avbroot/ota.py
There's no OnePlus-specific behavior here. ZERO blocks are supposed to be missing several fields, including data_sha256_hash.
=> avbroot/ota.py: Remove OnePlus comment about ZERO blocks

.gitignore, tests_ci/dummy_image.py, tests_ci/test_db.toml, tests_ci/test_device.py, tox.ini
Needs: #68 
Because testing the full OTA images in a CI would involve huge downloads, in this PR I introduce dummy images and a way to test them with tox.
I combined several commits in one PR as otherwise I would have to create a chain of PR's which all depends on each other.
Dummy images have some of the partitions which we don't care about (product, system, vendor, system_ext and modem) zeroed out. Zeroing these partitions allows them to be compressed very efficiently to somewhere around 70 MB. Because we now know which sections we do and don't need, with a simple mapping we can download only the sections of an image from the server (using the HTTP Range header) and assemble them locally. This creates an invalid zip file (CRC fails) on purpose to maintain the exact details of each zip. …
=> Use dummy images for testing

.github/actions/preload-img-cache/action.yml, .github/actions/preload-magisk-cache/action.yml, .github/actions/preload-tox-cache/action.yml, .github/workflows/ci.yml
Needs: #68 and #69
This PR adds CI for all devices using Github Actions. It at least allows us to automatically test the most used codepaths for all devices in combination with all Python versions. It tries to cache as much as possible to reduce burden on any external parties while at the same time parallelizing as much tests possible.
Maybe it is a bit much to test all images with all supported Python versions, but for now it is still manageable. 
The preloading is only done on the first run or when something changed in the database or `tox.ini`.
The Github cache gets removed after 7 days, but using a scheduled workflow we could keep the caches around for longer if that's desired.
The results of a full initial run can be seen [here](https://github.com/pascallj/avbroot/actions/runs/4284175 …
=> Test all device images in Github Actions

tests/README.md, tests/distros/Containerfile.alpine, tests/distros/Containerfile.arch, tests/distros/Containerfile.arch-wine, tests/distros/Containerfile.debian, tests/distros/Containerfile.fedora, tests/distros/Containerfile.opensuse, tests/distros/Containerfile.ubuntu, tests/distros/Containerfile.ubuntu-lts, tests/downloader.py, tests/tests.py
This PR introduces a custom parallel downloader for the tests. It replaces the current use of `aria2c` and can handle parallel downloads of either the entire file or of a list of byte ranges. It can be used as either a module or CLI tool.
Examples:
* Downloading an entire file:
```bash
python tests/download.py \
-u https://dl.google.com/dl/android/aosp/cheetah-ota-tq1a.230205.002-ad27a6d7.zip \
-o /tmp/test.zip
```
* Downloading specific ranges (and leaving the rest zeroed/untouched):
```bash
python tests/download.py \
-u https://github.com/topjohnwu/Magisk/releases/download/v25.2/Magisk-v25.2.apk \
-o /tmp/test.apk \
-r 0-16 \
-r 64-96
```
On my machine, it's consistently faster than aria2c. This might be because this implementation allows stealing half the work from another thread when …
=> tests: Add native Python parallel download implementation

.github/actions/preload-img-cache/action.yml, .github/workflows/ci.yml, tests_ci/dummy_image.py
As suggested in #70, creating sparse images for testing also works and saves on disk space and therefore also disk lifetime (be careful with your precious SSDs). Especially the Oneplus image is very big (4.8 GiB); this would consume 9.6 GiB during testing. This also comes somewhat close to the limit of 14 GB for the Github Runners. Now it would occupy 100 MiB actual disk space during testing. On top of that, it also makes the workflow faster.
The total workflow run time went down from 37m 50s to 33m 32s during the [Initial run](https://github.com/pascallj/avbroot/actions/runs/4315054599/attempts/1) and from 29m 30s to 26m 40s during a [subsequent run](https://github.com/pascallj/avbroot/actions/runs/4315054599/attempts/2) (and the runners even seem a bit slow at the moment).
Unfortunately …
=> Use sparse testing images

avbroot/ota.py, avbroot/util.py
This significantly reduces the size when patching dummy OTAs. This is a naive implementation that just seeks when the entire write() buffer is all zeroes, but that seems to be more than sufficient. The output files have fewer blocks allocated than the (dummy) input files.
=> Produce sparse output files

.github/actions/preload-magisk-cache/action.yml, .github/workflows/ci.yml
As mentioned in #75 there are more [restrictions on restoring the cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache) then first anticipated. This makes our current API checks kind of useless. This can be seen in [this](https://github.com/chenxiaolong/avbroot/actions/runs/4337696041/jobs/7573872981) run (which fails for an unrelated reason) where the preloading of the images is skipped during setup but all the caches are missed during the actual tests.
I created [a dedicated Github action](https://github.com/pascallj/cache-key-check) which checks the refs in (hopefully) the correct order to determine if a cache-key would create a cache-hit under the current circumstances without restoring it. There is no …
=> Make cache pre-checks more robust

.github/actions/preload-img-cache/action.yml, .github/actions/preload-magisk-cache/action.yml, .github/actions/preload-tox-cache/action.yml, .github/workflows/ci.yml
Now that https://github.com/actions/cache/pull/1041 is merged, we can use the `lookup-only` option, instead of my custom action. This is a much better solution. I didn't expect this to be merged so quickly :see_no_evil:.
The only downside is that the [actions/cache](https://github.com/actions/cache) also checks the version key, which is partly based on the path. So this must be duplicated. Also the `cache-hit` output is only set on a exact match and not on a prefix, so we use `cache-matched-key` instead to see if there is any hit. We were already using this all or nothing solution anyway.
=> Use `lookup-only` action to check if cache exists

README.md, avbroot/boot.py, avbroot/formats/compression.py, avbroot/main.py, avbroot/util.py, extra/cpiotool.py, tests/downloader.py, tests/tests.py
Newer Magisk versions no longer try to autodetect a writable ext4 partition for storing SELinux rules during boot. Instead, the block device is detected during boot image patching and is stored in the ramdisk's `.backup/.magisk` as `makedev(rdev_maj, rdev_min)`.
This unfortunately complicates the patching process for avbroot. Even if we replicate Magisk's algorithm for finding a suitable partition, there's no way to find the block device's rdev for it with the information contained in the OTA package. This is the first change that adds a hard dependency on information only attainable from a running device.
For these newer Magisk versions, the user will have to patch the boot image once in the Magisk app (must be on the target device) and then run `avbroot magisk-info` to show the computed …
=> Magisk >=25207 require a rules device ID

README.md, avbroot/boot.py, avbroot/main.py
Unlike the prior `RULESDEVICE`, `PREINITDEVICE` uses a block device name since the rdev major/minor is not guaranteed to remain the same across reboots. This commit completely drops support for `RULESDEVICE` (25207 through 25210) since it never made it to a stable Magisk release.
=> Switch to Magisk 25211's PREINITDEVICE

avbroot/boot.py, avbroot/main.py, tests/tests.py, tests/tests.yaml
In addition to the preinit device, Magisk now requires a random seed to be added to the Magisk config in the boot image. Magisk's boot_patch.sh generates a new seed every time an image is patched, but avbroot will use the hardcoded seed `0xfedcba9876543210` to guarantee byte-for-byte reproducibility of the output file. This can be overridden with `--magisk-random-seed <uint64>`.
=> Add support for Magisk >=25211

avbroot/boot.py
These versions are missing Magisk commit 1f8c063dc64806c4f7320ed66c785ff7bc116383, which fixes booting into recovery on devices that use Android 13 GKIs. Trying to use these versions with avbroot would prevent the user from installing future OTAs without manually flashing a boot image patched with a newer Magisk version while booted into Android first.
=> Drop support for Magisk versions <25102

README.md, avbroot/main.py
This allows users to use avbroot for just resigning an OTA with their own signing keys.
=> Add option to skip applying the root patch entirely

modules/build.py
=> modules/build.py: Windows requires `.bat` extension to be specified explicitly

README.md, avbroot/boot.py, avbroot/main.py
There are 3 levels of warnings:
* Level 0: Warnings that don't affect booting
* Mismatched `id` or `os_version` fields
* Level 1: Warnings that may affect booting
* Mismatched `cmdline` or `extra_cmdline` fields
* Unexpected addition of `kernel`, `second`, `recovery_dtbo`, `dtb`, or `bootconfig`
* Level 2: Warnings that are very likely to affect booting
* All other mismatched, added, or removed fields
By default, any warning of level 1 or higher is treated as a fatal error. Each time `--ignore-prepatched-compat` is passed in, the permitted warning level is increased.
Fixes: #108
=> Add support for ignoring boot image checks for --prepatched

README.md, avbroot/main.py, avbroot/vbmeta.py, tests/tests.py, tests/tests.yaml
This commit adds support for replacing any partition image within the payload with a custom image. This is useful, for example, to add a custom kernel to an OTA, which may involve partitions that wouldn't normally be touched (eg. `vendor_dlkm`).
Any image specified via `--replace` will have its corresponding descriptor in the vbmeta image updated. This is handled recursively. For example, replacing `vendor_dlkm` would update both `vbmeta_vendor` and `vbmeta`. This requires all vbmeta images to be extracted during the patching process so that a complete dependency graph can be computed. The performance hit in doing so is negligible, but does require the checksums of the stripped images to be updated for the tests.
Fixes: #102
=> Add support for replacing any partition image

avbroot/main.py, tests/tests.yaml
PR #110 fixed this incorrectly. I misinterpreted "set to zero in the local header" from §4.4.4 in the spec as referring to the two 32-bit size fields in the local header. However, the spec considers the zip64 extra record as part of the local header. The correct behavior for writing zip64 entries to unseekable files is `0xffffffff` in the 32-bit local header size fields (to enable zip64), `0` in the zip64 extra record (due to streaming writes), and the actual sizes in the data descriptor.
Fixes: #109
=> Ensure output files are zip64-compliant (again)

avbroot/main.py, avbroot/util.py
We have to emulate this with fchmod because Python's NamedTemporaryFile always opens the file descriptor with 600 permissions.
=> Make output file permissions respect umask

avbroot/src/boot.rs
There are no changes that break avbroot.
=> boot.rs: Allow Magisk 263xx

avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs
This way, the payload-related functions can be used to parse incremental OTA files.
=> Move full OTA check to patch/extract subcommand function

avbroot/src/format/payload.rs, e2e/e2e.toml
This fixes `data_offset` being set for `ZERO` and `DISCARD` operations, which prevents some images (eg. `ossi`) from being flashed due to update_engine's strict field validation.
=> PayloadWriter: Only set data_offset for operations that reference blobs

Cargo.lock, avbroot/Cargo.toml, deny.toml
When using the `xz2/static` feature, the xz2 crate uses a bundled version of xz 5.2 and doesn't enable all of the available encoders and decoders. This prevents certain payload data from being decompressed.
Fixes: #138
=> Upgrade xz to 5.4.4 and enable all encoders and decoders

Cargo.lock, e2e/Cargo.toml, e2e/src/download.rs, e2e/src/main.rs
We don't use async for anything else, so switching to a synchronous HTTP library lets us get rid of the entire async ecosystem and removes 47 packages from e2e's dependency tree.
The only downside is that ^C worst case takes 5 seconds (TCP connect and read timeouts) or whatever the OS's DNS lookup timeout is. That's good enough for a test suite.
Performance wise, e2e still easily saturates a gigabit internet connection.
=> e2e: Switch to attohttpc for HTTP downloads

avbroot/src/boot.rs, avbroot/src/cli/args.rs, avbroot/src/cli/avb.rs, avbroot/src/cli/ota.rs, avbroot/src/format/avb.rs, avbroot/src/format/ota.rs, avbroot/src/format/payload.rs, avbroot/src/stream.rs, e2e/src/download.rs, e2e/src/main.rs
There's no reason all these functions need to care about the ownership of the cancel signal.
=> Stopping spewing Arc everywhere for the cancel signal

Cargo.lock, README.extra.md, avbroot/Cargo.toml, avbroot/src/cli/args.rs, avbroot/src/cli/avb.rs, avbroot/src/cli/fec.rs, avbroot/src/cli/mod.rs, avbroot/src/cli/ota.rs, avbroot/src/format/avb.rs, avbroot/src/format/fec.rs, avbroot/src/format/mod.rs, avbroot/src/format/verityrs.rs, avbroot/src/stream.rs
This commit adds initial support for the FEC (forward error correction) used by dm-verity. The new `avbroot fec` commands operate on FEC data stored in AOSP's standalone FEC file format. It is compatible with AOSP's `fec` tool.
Issue: #145
=> Add support for AVB FEC

CHANGELOG.md, xtask/src/changelog.rs
The longer PR links have weird line wrapping behavior on the Github web UI, making it more difficult to read.
=> Shorten changelog links

Cargo.lock, Cargo.toml, fuzz/.gitignore, fuzz/Cargo.toml, fuzz/README.md, fuzz/hfuzz_workspace/avb/input/vbmeta_appended_hash.img, fuzz/hfuzz_workspace/avb/input/vbmeta_appended_hash_tree.img, fuzz/hfuzz_workspace/avb/input/vbmeta_root.img, fuzz/hfuzz_workspace/bootimage/input/boot_v0.img, fuzz/hfuzz_workspace/bootimage/input/boot_v1.img, fuzz/hfuzz_workspace/bootimage/input/boot_v2.img, fuzz/hfuzz_workspace/bootimage/input/boot_v3.img, fuzz/hfuzz_workspace/bootimage/input/boot_v4.img, fuzz/hfuzz_workspace/bootimage/input/boot_v4_vts.img, fuzz/hfuzz_workspace/bootimage/input/vendor_v3.img, fuzz/hfuzz_workspace/bootimage/input/vendor_v4.img, fuzz/src/bin/avb.rs, fuzz/src/bin/bootimage.rs
This initially includes fuzzers for the AVB and boot image parsers. The initial input corpus are the same test files we use for the round trip tests.
Issue: #160
=> Add initial honggfuzz fuzzing infrastructure

avbroot/src/format/avb.rs
(Found by honggfuzz)
Issue: #160
=> avb: Use checked addition when computing auth/aux block size

avbroot/src/format/ota.rs
This way we can't run out of memory if the zip entry lists an invalid file size that's much bigger than the actual file.
Issue: #157
=> ota: Don't preallocate buffer when reading OTA metadata

avbroot/src/format/fec.rs, avbroot/src/format/payload.rs
This is the only part of the payload that we have to read entirely into memory. The limit is currently set to 1 MiB, which is around ~5-6x the manifest size in all the e2e test suite's images.
Issue: #169
=> payload: Add size limit for protobuf manifest

Cargo.lock, avbroot/Cargo.toml, avbroot/src/cli/avb.rs, avbroot/src/cli/ota.rs, avbroot/src/util.rs, deny.toml
This prevents avbroot writing to locations where it shouldn't due to manipulation from external processes. For example, replacing the output directory for `avbroot ota extract` with a symlink.
Regardless of what symlinks or other changes an external process does to the directory, the cap-std library will use the appropriate `openat2()` options (or equivalent) to prevent writes outside of the directory.
Fixes: #166
=> Use handle-based directory operations instead of path-based

README.extra.md, avbroot/src/cli/boot.rs, avbroot/src/format/bootimage.rs
This also changes the serialization to use a `type` field instead of spewing the enum variant name everywhere.
=> boot: Rename header.toml to boot.toml for consistency

Cargo.lock, avbroot/Cargo.toml, avbroot/build.rs, avbroot/src/cli/ota.rs, avbroot/src/format/ota.rs, avbroot/src/format/payload.rs, avbroot/src/protobuf.rs, avbroot/src/util.rs, e2e/e2e.toml, e2e/src/main.rs
There are several things we had to work around with quick-protobuf, like forcing no_std mode to use BTreeMaps and avoiding helper functions to read and write non-size-delimited messages. In addition, the pb-rs code generator doesn't support adding #[derive]s to enums and the existing support for adding derives to structs is broken due to incorrect string concatenation.
Prost doesn't have these limitations and bugs. I originally avoided it because prost_build required the external `protoc` binary, but now that the protox library exists, the code generation can be done entirely in Rust without external tools.
Prost also fully supports adding custom attributes to structs, enums, and fields. This will be helpful for future payload unpack and pack commands where the payload manifest would have …
=> Switch to prost for protobuf encoding/decoding

avbroot/src/format/payload.rs
The Android 13 -> 14 incremental OTA has a 1.7 MiB manifest.
=> payload: Bump maximum manifest size to 4 MiB

avbroot/src/cli/avb.rs, avbroot/src/cli/fec.rs, avbroot/src/cli/ota.rs, avbroot/src/format/avb.rs, avbroot/src/format/fec.rs, avbroot/src/format/payload.rs, avbroot/src/stream.rs, avbroot/tests/avb.rs, e2e/src/download.rs, e2e/src/main.rs, fuzz/src/bin/fec.rs
This is still not the ideal API, but it makes the code quite a bit more readable since we no longer have to pass around closures everywhere that multithreaded reads and writes to the same file are needed.
=> Move reopen functionality to a new trait

avbroot/src/format/avb.rs
Some partitions, like system_ext in the Pixel Experience build for `avicii`, use SHA1 for the dm-verity hash tree. This is technically valid, so allow the `avb verify` command to compute these hashes. SHA1 will still be rejected when creating AVB images.
=> avb: Allow computing insecure SHA1 hashes for verification

avbroot/src/boot.rs, e2e/e2e.toml
Previously, the AVB `algorithm_type` field was unconditionally being set to a value that is compatible with the AVB private key. However, for indirectly-signed boot images, the value should be set to `None`. Pixel bootloaders accept the incorrect value, but other devices' bootloaders might not.
Issue: #186
=> boot: Avoid setting signature algorithm when image is indirectly signed

README.md, avbroot/src/cli/ota.rs, avbroot/src/format/ota.rs
Android 11 OTAs use the same `payload.bin` format, but lack the `metadata.pb` protobuf representation of the OTA metadata. This commit adds support for parsing the legacy plain-text `metadata` format. Like before, the output files will still contain both the legacy and protobuf representations.
Note that the legacy format allowed OEMs to specify arbitrary key/value pairs. These will be discarded during patching because they cannot be represented in the protobuf format, which is used in avbroot's internal representation.
Issue: #195
=> ota: Add support for legacy OTA metadata

avbroot/src/boot.rs
There are no upstream changes that impact avbroot.
=> boot.rs: Bump Magisk version upper bound to 26500

avbroot/src/cli/avb.rs, avbroot/src/format/avb.rs
Older Pixel devices (and ChromiumOS) specify the dm-verity options on the kernel command line using a custom `dm=` parameter instead of using dm-init or a userspace helper. This commit updates the avb pack and repack commands to automatically update the relevant kernel command line descriptor if it exists.
Issue: #203
=> cli/avb: Update kernel cmdline descriptor for devices that use `dm=`

README.extra.md, avbroot/src/cli/avb.rs
This is done unconditionally because there shouldn't be any real-world device that uses AVB2 and has a kernel compiled without sha256 support.
Issue: #203
=> cli/avb: Promote insecure hash algorithms to secure ones

avbroot/src/format/avb.rs
Format version 1.3.0 adds a new 32-bit big endian `flags` field to chain descriptors, carved out from the `reserved` array. There is only one possible flag, which indicates that the target partition is not A/B and so the bootloader should not append the `_a` or `_b` suffix.
There are no known AVB images in the wild where the first four bytes of the `reserved` field are not zero. Thus, to keep the logic simple, the AVB parser will unconditionally parse those bytes as if they were the `flags` field, regardless of the file format version.
AOSP changes:
* https://android.googlesource.com/platform/external/avb/+/a1fe228b86543a21739c51352f5ce72f134fccfa%5E%21/
* https://android.googlesource.com/platform/external/avb/+/d00d02c390e267ef43d93562864dd6e45966c435%5E%21/
=> avb: Add support for AVB 2.0 format 1.3.0

deny.toml
https://rustsec.org/advisories/RUSTSEC-2023-0071
This is a side-channel vulnerability where secrets can be leaked to an attacker that is able to measure the timing of a large number of RSA operations. As of 2023-12-03, there is no released version of the rsa crate that contains a fix.
For avbroot specifically, this vulnerability is not too critical for a couple reasons:
1. avbroot performs RSA signing only at the end of lengthy processes that involve a lot of disk I/O. It's very expensive to run avbroot the millions of times needed to capture a sufficient amount of timing data.
2. During a single run of avbroot, it will only perform RSA signing a handful of times. To get sufficient measurements, the attacker would need to rerun avbroot. If they are able to rerun avbroot, then they are …
=> deny.toml: Temporarily ignore RUSTSEC-2023-0071

avbroot/src/cli/key.rs, avbroot/src/crypto.rs
This does the reverse of `avbroot key extract-avb`. It's useful for reconstructing a PKCS8-encoded RSA public key when working with the `public_key` fields in `avb.toml`.
=> key: Add new decode-avb subcommand

avbroot/src/cli/ota.rs
AOSP primarily cares about `odm` and `odm_dlkm`, so update the logic to check for that specifically. This fixes patching some OTAs that include an unprotected OEM-specific `odm_ext` image.
Issue: #218
=> cli/ota: Fine tune `is_critical_to_avb()` for odm partition

avbroot/src/cli/ota.rs, e2e/src/main.rs
The autodetection logic for `@otacerts` is based on the presence of the `recovery`, `vendor_boot`, and `boot` partitions (in that order). Some devices have `vendor_boot`, but put `system/etc/security/otacerts.zip` inside `boot`.
With the way things are written now, we don't have the ability to inspect the actual partition images for the autodetection. It is based on the name only. So, for now, we'll just allow the user to override the autodetected partition similar to what we already do with the `--boot-partition` option.
Issue: #218
=> cli/ota: Add new --otacerts-partition option for the patch subcommand

.github/actions/preload-img-cache/action.yml, .github/actions/preload-magisk-cache/action.yml, .github/workflows/ci.yml
This way, the precompiled executables can run on distros that ship an older version of glibc or don't use glibc at all.
Fixes: #222
=> workflows/ci: Build statically linked executables where possible

avbroot/src/cli/ota.rs
dm-verity partitions don't necessarily have AVB descriptors inside the root vbmeta images. The fstab might verify them against a public key on disk using the `avb_keys` fs_mgr option. We have no way to statically check for this scenario and it's becoming increasingly common on newer OnePlus devices. Instead, we'll just limit the checks to partitions that are verified by the bootloader.
Fixes: #223
=> cli/ota: Limit critical partition check to bootloader-verified partitions

README.extra.md, avbroot/src/cli/fec.rs, avbroot/src/format/fec.rs, avbroot/src/util.rs, e2e/src/main.rs
FEC data can be updated efficiently with "round" granularity when the regions where the input file was modified are known.
=> fec: Add support for partially updating FEC data

avbroot/src/format/avb.rs
This isn't something we'd ever run into in practice because Android only puts real filesystems inside dm-verity and a real filesystem can't be smaller than one block.
=> avb: hashtree: Fix incorrect I/O read size for input smaller than one block

README.extra.md, avbroot/src/cli/args.rs, avbroot/src/cli/avb.rs, avbroot/src/cli/hashtree.rs, avbroot/src/cli/mod.rs, avbroot/src/format/avb.rs, avbroot/src/format/fec.rs, avbroot/src/format/hashtree.rs, avbroot/src/format/mod.rs
* Refactor hash tree computation to work on a preallocated hash tree buffer. This makes it possible to partially update a hash tree, which is now supported.
* Add new subcommands for working with hash trees. There's no standard header format for dm-verity information, so these commands write hash tree files with a custom header. The commands are not really useful outside of debugging avbroot's hash tree implementation.
Using AVB was considered, but it has no support for the hash tree data living in a separate file from the input. If other parties agree on a standard header in the future, avbroot will switch to that format.
* Add tests for the hash tree implementation.
=> Split dm-verify hash tree logic out of avb module

README.md, avbroot/src/boot.rs, avbroot/src/cli/ota.rs, e2e/e2e.toml, e2e/src/main.rs
During patching, all boot images are now extracted and the individual patchers can inspect them to determine which ones need modifications. This replaces the previous mechanism of detecting which boot images to patch based on the name alone.
With this new method, the `--boot-partition` and `--otacerts-partitions` options are no longer needed. The former option is kept (but ignored with a warning message) for backwards compatibility, but the latter is completely removed because it never made it to a stable release.
=> Allow boot image autodetection to inspect boot images

Cargo.lock, README.md, avbroot/Cargo.toml, avbroot/src/cli/avb.rs, avbroot/src/cli/ota.rs, avbroot/src/format/avb.rs, avbroot/src/format/hashtree.rs, avbroot/src/format/ota.rs, avbroot/src/lib.rs, avbroot/src/patch/boot.rs, avbroot/src/patch/mod.rs, avbroot/src/patch/otacert.rs, avbroot/src/patch/system.rs, avbroot/tests/avb.rs, e2e/src/main.rs, modules/clearotacerts/module.prop, xtask/src/module.rs
Previously, overriding `otacerts.zip` in the system partition required the user to flash a Magisk/KernelSU module that would bind mount over the file during boot. While this worked well enough, it's insufficient for unrooted setups, which has become more important since unrooting is the only safe way to use the new OEM repair mode feature. With the stock `otacerts.zip`, the OEM's default OTA updater app could run and install an OS upgrade that's not signed by the user's key.
With this commit, the raw `otacerts.zip` bytes in the system partition are directly replaced with a new zip that contains the user's certificate. This method was inspired by @pascallj's comment in #216 suggesting intentionally corrupting the `otacerts.zip` data in the filesystem.
Because avbroot does not have …
=> Add support for replacing otacerts.zip in the system image

avbroot/src/cli/ota.rs, avbroot/src/format/hashtree.rs, avbroot/src/format/payload.rs, avbroot/src/patch/system.rs, avbroot/src/util.rs
When the original payload extents are all in order and have no gaps, we can efficiently copy unmodified chunks of the system image from the original payload into the new payload. Only the chunks containing the modified regions (`otacerts.zip`, hash tree, FEC data, and AVB metadata) need to be recompressed. This massively reduces the CPU usage since usually only <20 MiB need to be recompressed.
If the conditions for the optimized path aren't satisfied (eg. extents aren't in order or `--replace` is used), then it falls back to splitting and compressing the entire system image.
This fixes the performance issues introduced in #240. This is probably the best that we can do given that we now always patch the system image.
Issue: #225
=> Optimize repacking of modified system image into payload

README.md
=> README.md: Document Repair Mode

Cargo.lock, avbroot/Cargo.toml, avbroot/src/format/compression.rs, avbroot/src/format/payload.rs, avbroot/src/patch/boot.rs, deny.toml
liblzma is a maintained fork of xz2. We can now get rid of our own fork of xz2.
=> Switch from xz2 to liblzma

avbroot/src/patch/boot.rs, e2e/e2e.toml, e2e/src/main.rs
Upstream Magisk now xz-compresses files in modifies in the ramdisk. This commit also implements the same in avbroot's MagiskRootPatcher.
=> Add support for Magisk v27.0

Cargo.lock, avbroot/Cargo.toml, avbroot/src/cli/args.rs, avbroot/src/cli/avb.rs, avbroot/src/cli/mod.rs, avbroot/src/cli/ota.rs, avbroot/src/main.rs, avbroot/src/patch/boot.rs, avbroot/src/patch/otacert.rs, avbroot/src/patch/system.rs, e2e/Cargo.toml, e2e/src/cli.rs, e2e/src/main.rs
Instead of println'ing everything, this commit switches the code base to using the tracing library. There are now proper log levels and multiple logging output formats. A bunch of new debug and trace-level messages have also been added to help with future troubleshooting.
<details>
<summary>EDIT: Ugly structured logging is no longer used</summary>
The output is a bit uglier than before due to liberal use of spans and structured logging. We can tweak the message formatting later if needed.
Screenshots:
* [`--log-format short` (Default)](https://github.com/chenxiaolong/avbroot/assets/646253/39326f3a-dcf2-4d97-88eb-70feff524c80)
* [`--log-format medium`](https://github.com/chenxiaolong/avbroot/assets/646253/82e33ddb-3da8-4701-9124-2c2ff072d2a7)
* [`--log-format …
=> Add tracing support

avbroot/src/crypto.rs
x509_cert is unable to parse files that contains non-empty lines outside of the BEGIN CERTIFICATE and END CERTIFICATE markers.
=> crypto: reformat_pem: Strip out irrelevant lines

README.md, avbroot/src/cli/ota.rs
`fastboot flashall` is identical to the `fastboot update` command used by the Pixel factory images, except it reads from a directory instead of a zip file. It knows how to flip between the fastboot and fastbootd modes without user intervention.
Fixes: #252
=> Use `fastboot flashall` to flash partitions initially

Cargo.lock, avbroot/Cargo.toml, deny.toml
This includes a fix for yet another infinite-loop-on-drop bug in the bzip2::write::BzDecoder implementation. This could be easily triggered when interrupting an avbroot command while it is extracting a bzip2 compressed payload.bin chunk.
Fixes: #285
=> Switch to my fork of the bzip2-rs library

README.md, avbroot/src/cli/ota.rs, avbroot/src/patch/boot.rs, e2e/e2e.toml, e2e/src/config.rs, e2e/src/main.rs
This allows the user to boot GSIs signed by the same key. The option is disabled by default because some Android builds disable DSU support by removing all keys to reduce the attack surface. We don't want to reenable DSU support on these builds unless the user asks for it.
Closes: #286
=> Add support for adding AVB public key to DSU trusted keys

avbroot/src/format/avb.rs, avbroot/src/format/fec.rs, avbroot/src/format/hashtree.rs, avbroot/src/format/payload.rs, avbroot/src/patch/system.rs, avbroot/src/util.rs
Fixes: https://github.com/chenxiaolong/avbroot/issues/291
=> avb: Bump hashtree and FEC size limits to accommodate 8 GiB images

README.extra.md, avbroot/src/cli/avb.rs
Previously, there was no way to easily see the values of the recomputed fields without unpacking the newly built image. This commit adds a new `--output-info` option to the `avb pack` subcommand to write/overwrite a new `avb.toml` file.
=> cli/avb: Allow writing new TOML file when packing an image

CHANGELOG.md, avbroot/src/patch/boot.rs
Magisk no longer puts both magisk64 and magisk32 in the ramdisk. Instead, it just puts a single binary for the target ABI.
=> Add support for upcoming Magisk Canary 27003

.github/workflows/ci.yml, README.md
The precompiled binaries are compiled for aarch64 API 31, which should work for every device that avbroot supports.
=> Add support for cross-compiling to Android

avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs, e2e/e2e.toml, e2e/src/main.rs
Otherwise, if the partition size increases or the data becomes more incompressible, update_engine might fail to flash the partition due to the CoW block device running out of space.
Since all known VABC-enabled OTAs in the wild currently use CoW v2 with lz4 compression, this is the only configuration we support. CoW v3 also exists in AOSP's libsnapshot_cow, but is much more complicated to implement and is not yet used, even in the Android 15 beta OTAs.
Fixes: #306
=> Update CoW size estimate when replacing entire dynamic partitions

README.extra.md, avbroot/src/cli/args.rs, avbroot/src/cli/mod.rs, avbroot/src/cli/payload.rs
I'm tired of adding `println!("{header:#?}")` to troubleshoot things. Let's add an actual subcommand for dumping the headers of `payload.bin` files.
=> Add payload subcommand for dumping payload.bin header

avbroot/src/format/avb.rs
This is never reachable due to additional checks in every code path that invokes `sign()` and `verify()`, but still better to be correct.
=> avb: AlgorithmType: Fail on unknown key types

Cargo.lock, deny.toml
Version 1.6.0 of the bytes library was yanked. There's no vulnerability that impacts avbroot, but it was tripping the cargo-deny checks.
=> Update all dependencies

avbroot/src/patch/boot.rs, e2e/e2e.toml, e2e/src/main.rs
Version 27006 now requires `init-ld` to be included in the ramdisk.
=> Add support for Magisk 27006

Cargo.lock, README.extra.md, avbroot/Cargo.toml, avbroot/build.rs, avbroot/src/cli/args.rs, avbroot/src/cli/cpio.rs, avbroot/src/cli/ota.rs, avbroot/src/cli/payload.rs, avbroot/src/format/payload.rs, e2e/src/main.rs
Some devices have "full" OTAs where the payload is missing the recovery partition. These subcommands make it possible to manually add back the missing image. Given the strict requirements for how the OTA zip is laid out and signed, users can't just replace `payload.bin` in a zip and call it a day, but it's sufficient for feeding a modified input to `avbroot ota patch`.
Issue: #328
=> Add subcommands for packing and unpacking payload binaries

Cargo.lock, avbroot/Cargo.toml, avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs, e2e/e2e.toml, e2e/src/config.rs, e2e/src/main.rs
Older devices, like the Pixel 4a 5G (bramble) use gzip instead of lz4.
This commit also reworks the CoW size estimate calculation to add the same constant headroom that AOSP's delta_generator adds. Previously, avbroot was already adding an additional 1% to account for differences in compression ratios across compression library implementations. This papered over the issue for large partitions, but small partitions could still have a CoW size estimate that's too small. Adding the constant headroom prevents ENOSPC when flashing those partitions.
Fixes: #332
=> Add support for gzip VABC algorithm

Cargo.lock, avbroot/Cargo.toml, avbroot/src/crypto.rs
`ENXIO` (No such device or address) and `ENOTTY` (Inappropriate ioctl for device) are not very user-friendly error messages.
Issue: https://github.com/chenxiaolong/my-avbroot-setup/issues/2
=> Print a useful error message when there's no TTY for a password prompt

README.md, avbroot/src/cli/ota.rs, avbroot/src/format/ota.rs, avbroot/src/stream.rs, e2e/e2e.toml, e2e/src/config.rs, e2e/src/main.rs
This commit adds a new `--zip-mode` parameter to `avbroot ota patch` to control whether the patched OTA zip is written with data descriptors or not. By default, the `streaming` mode is used, which matches the current behavior where the zip is hashed for signing as it is being written. The new `seekable` mode fully writes the zip before rereading it to hash the contents.
The new mode is useful for devices with broken zip parsers that fail to properly handle data descriptors.
All of the end-to-end tests have been duplicated to test both modes.
Adding the seekable mode necessitated a couple other changes:
* BufWriter is no longer used. Type erasure is very painful in Rust, so we need to keep the writer types the same for both the streaming and seekable modes. BufWriter is unusable in the …
=> Add support for outputting zip files with no data descriptors

Cargo.lock, README.extra.md, avbroot/Cargo.toml, avbroot/src/cli/args.rs, avbroot/src/cli/lp.rs, avbroot/src/cli/mod.rs, avbroot/src/cli/payload.rs, avbroot/src/format/lp.rs, avbroot/src/format/mod.rs, avbroot/tests/lp.rs, fuzz/src/bin/lp.rs
This supports both empty and normal LP images, including those that span multiple files/devices.
Currently, repacked files are semantically equivalent, but not exactly identical. avbroot's data structure for the metadata does not preserve the arbitrary partition ordering of the LP image. Instead, to make the API a bit nicer, it only preserves the relative partition ordering within partition groups.
=> Add support for packing and unpacking logical partition images

README.extra.md, avbroot/src/cli/lp.rs
Empty images don't contain any extent metadata so the partition sizes are just discarded.
Don't write parsers when you're tired, folks!
=> lp: Sparse files are not required when packing and unpacking empty images

Cargo.lock, README.extra.md, avbroot/Cargo.toml, avbroot/src/cli/args.rs, avbroot/src/cli/mod.rs, avbroot/src/cli/sparse.rs, avbroot/src/format/lp.rs, avbroot/src/format/mod.rs, avbroot/src/format/sparse.rs, avbroot/tests/sparse.rs, deny.toml, fuzz/src/bin/sparse.rs
This supports all features of Android sparse images, including holes, and CRC32 (both full image checksum and CRC32 chunks).
Partial sparse images, like those included in GrapheneOS' new optimized factory images, can also be packed and unpacked with these new commands, unlike AOSP's simg2img and img2simg tools.
This new functionality is not relevant for avbroot's main use case, but is useful for unpacking certain factory images for comparison with OTAs during troubleshooting.
=> Add support for packing and unpacking Android sparse images

avbroot/src/main.rs
`std::process::exit()` calls the exit syscall, which doesn't run destructors. It doesn't matter for avbroot, but better to use `ExitCode` anyway.
=> Return ExitCode from main

README.extra.md, avbroot/src/cli/payload.rs
The pack and unpack commands can never support delta payloads, but there's no reason not to allow the repack and info commands to read them.
=> cli/payload: Allow inspecting delta payloads

Cargo.lock, avbroot/Cargo.toml, avbroot/src/crypto.rs
This library behaves exactly the same as rpassword, but has zero dependencies so we no longer need to pull in the ancient windows-sys 0.48.x libraries.
We still transitively depend on both windows-sys 0.52.x and 0.59.x though.
=> Switch to passterm library for password prompts

avbroot/src/cli/ota.rs, e2e/src/main.rs
On older devices, like the Pixel 4a, where `boot` is used for both Android and recovery mode, the image will be patched by `OtaCertPatcher` and `PrepatchedImagePatcher`. `OtaCertPatcher` was always set to run first, so when `PrepatchedImagePatcher` used the user-supplied image as-is, prior modifications got wiped out. This made is so users could no longer flash further patched OTAs.
This is an unfortunate regression that was introduced in avbroot 2.0.0. The e2e tests never caught this issue because the `--prepatched` test was being fed the boot image previously patched by `--magisk`. That already had valid certs so the result of `OtaCertPatcher`'s modifications being lost were not visible. This commit also fixes the e2e tests so that this type of issue will be caught in the future.
Fixes: …
=> Ensure that PrepatchedImagePatcher runs before other patchers

.github/workflows/ci.yml
Otherwise, the x86_64-unknown-linux-gnu build running on Ubuntu 22.04 can use the cache from the aarch64-linux-android31 build that originally ran on Ubuntu 24.04. This fails due to some cached components having been compiled against a newer version of glibc.
=> ci.yml: Use target name in Rust cache key

README.extra.md, avbroot/src/cli/avb.rs
This computes the special SHA256 digest that is equal to the `ro.boot.vbmeta.digest` property value on a real device.
=> cli/avb: Add subcommand for computing vbmeta digest

README.md, avbroot/src/cli/ota.rs, avbroot/src/patch/boot.rs
=> Add option to skip inserting OTA cert into recovery image

avbroot/src/cli/avb.rs, avbroot/src/cli/ota.rs
Previously, it was not always obvious which key was problematic.
Issue: #366
=> Add more context for avb::Header::set_algo_for_key() calls

avbroot/src/format/payload.rs
Older OTAs created before the payload metadata format supported EC signatures will not have the `unpadded_signature_size` field set. In this case, we'll just use the full length of `data`, which is what update_engine also does.
Issue: #366
=> format/payload: Allow verifying signatures without an unpadded size

avbroot/src/format/sparse.rs
The official AOSP implementation does, so we should too. This allows unpacking Samsung's sparse images, which have an extra 4 bytes in both the file header and chunk headers.
=> sparse: Allow parsing files with unknown fields

avbroot/src/format/avb.rs, avbroot/src/format/bootimage.rs, avbroot/src/format/cpio.rs, avbroot/src/format/fec.rs, avbroot/src/format/hashtree.rs, avbroot/src/format/lp.rs, avbroot/src/format/payload.rs, avbroot/src/format/sparse.rs, avbroot/src/patch/system.rs, avbroot/src/stream.rs, avbroot/src/util.rs
* Remove the `ReadString` trait and perform UTF-8 conversions explicitly. UTF-8 conversion errors are now individual errors instead of being hidden in an `Io` error.
* Add new `IntOutOfBounds` errors that include the actual field value and the range of values that are valid for the field. Integer casting also uses this error type where possible.
* Replace remaining uses of `FieldOutOfBounds` with `IntOverflow`, which is returned when checked arithmetic fails. For code simplicity, it does not store intermediate values.
* Replace `ReadFieldError` and `WriteFieldError` with the generic `Io` error to simplify the code. They were used inconsistently anyway.
* Use fully qualified field names in `avb` and `bootimage` error messages since the same name frequently appears in multiple structs.
* …
=> Improve parser error messages

avbroot/src/patch/boot.rs
There is nothing new that breaks compatibility with avbroot.
Fixes: #389
=> Add support for Magisk 28100

avbroot/src/patch/boot.rs
`MagiskRootPatcher` was previously assuming that there is a preinit device value if the Magisk version requires it.
=> Fix crash when ignoring warning about missing preinit device

avbroot/src/patch/boot.rs
Previously, when patching with a Magisk version newer than the latest supported version and using `--ignore-magisk-warnings`, the upper bound of `VER_PREINIT_DEVICE` and `VER_XZ_BACKUP` would prevent those features from being used. It makes more sense to assume that a newer version supports all the same features as the latest supported version instead.
Issue: #393
=> Treat Magisk versions newer than latest as supporting all features

Cargo.lock, avbroot/Cargo.toml, deny.toml
The bzip2-rs library now has a new maintainer (same folks that maintain the sudo-rs project). Version 0.5.0 was recently released, which includes some much needed bug fixes, but is missing one final one, so we still need to keep our fork for now.
This commit also switches the backend implementation from the official C implementation to a Rust implementation maintained by the bzip2-rs folks. This leaves xz as the only C dependency remaining in avbroot.
=> Update bzip2-rs to 0.5.0 and switch to Rust backend implementation

avbroot/src/cli/avb.rs, avbroot/src/cli/ota.rs, avbroot/src/crypto.rs, avbroot/src/format/avb.rs, avbroot/src/format/bootimage.rs, avbroot/src/format/compression.rs, avbroot/src/format/cpio.rs, avbroot/src/format/fec.rs, avbroot/src/format/hashtree.rs, avbroot/src/format/lp.rs, avbroot/src/format/ota.rs, avbroot/src/format/payload.rs, avbroot/src/format/sparse.rs, avbroot/src/patch/boot.rs, avbroot/src/patch/otacert.rs, avbroot/src/patch/system.rs, e2e/src/main.rs
Implicit error propagation was originally used because it was convenient and made it easy to just bubble up errors via the `?` operator without thinking. However, there have been too many situations where this resulted in error messages that were completely useless in troubleshooting the problem. `I/O error`, even with a specific reason attached, is useless where there are potentially hundreds of operations where I/O can fail.
I no longer think implicit error propagation is a good idea, so this commit removes every single use of `#[from]` in every custom error type. There are now many more error variants, allowing more context to be attached to the underlying errors.
Previously, it was easy to encounter error messages like:
Caused by:
0: Failed to patch payload: payload.bin
1: Failed to …
=> Remove all uses of implicit error propagation

Cargo.lock, avbroot/Cargo.toml, deny.toml
The only remaining fix from our fork has been merged. This can be switched to a stable release after the next release.
=> Switch to upstream master branch of bzip2-rs

avbroot/src/format/cpio.rs
Avoids doing 14 small reads per cpio entry.
=> cpio: Read and write entire header at once

README.md, avbroot/src/cli/ota.rs
Previously, we only supported extracting all images or the subset of images that could potentially be patched by avbroot. This was unnecessarily slow if the user only needed to extract a specific image.
This commit also deprecates and hides the `--boot-only` option, though the functionality will remain indefinitely.
=> cli/ota: Add support for extracting specific images

README.md, avbroot/src/cli/ota.rs, avbroot/src/crypto.rs, avbroot/src/format/ota.rs
This also adds a new `--none` option so that these two components can be extracted without extracting any partition images.
=> cli/ota: Add support for extracting OTA certificate and AVB public key

README.md, avbroot/src/cli/ota.rs
This is analogous to the existing `--skip-recovery-ota-cert` option, except for the system image.
Discussion: #417
=> Add option to skip replacing OTA cert in system image

Cargo.lock, avbroot/Cargo.toml, avbroot/src/format/payload.rs, deny.toml, e2e/e2e.toml
* There is now a stable release of bzip2-rs with the fix for both the C and Rust versions of bzip2 being compiled.
* The zlib-rs deflate implementation is faster than the default miniz_oxide. Changing this requires updating the checksums in the e2e tests due to slight differences in compression levels between the two implementations.
* Temporarily silence RUSTSEC-2025-0007 to avoid blocking CI. The ring library is no longer maintained.
=> Switch to stable bzip2-rs release and use zlib-rs flate2 backend

avbroot/src/cli/ota.rs
The filtering out of partitions was done at the wrong scope, causing avbroot to warn that extracted-but-unmodified partitions were not protected by AVB. We never encountered this before because the system image was always patched and unmodified boot images got filtered out at an earlier phase during patching.
=> cli/ota: Fix incorrect unprotected partition warning with --skip-system-ota-cert

avbroot/src/cli/ota.rs
This is the same optimization as is currently done for boot images. There's no reason to keep the temp file around for the entire patching process if it's unmodified and we're not going to be copying its data into the payload.
=> cli/ota: Discard unmodified system image temp file earlier

avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs, e2e/e2e.toml
Instead of compressing the 64 MiB input in 2 MiB chunks, each loop iteration was compressing the full 64 MiB. This massively slowed down the patching process from seconds to potentially hours and would temporarily waste a bunch of space during OTA installation.
Fixes: #433
=> Fix incorrect compression input for gzip CoW size estimation

README.md, avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs, e2e/e2e.toml
Devices that launch with Android <14 generally use gzip as the CoW compression algorithm. This never changes because future full OTAs always need to be installable from the version of Android the device launched with.
However, for users that don't care about the upgrade path from old versions of Android, a new `--vabc-algo` option can be used to switch from gz to lz4 compression. This can cut down the OTA installation time by more than 2/3rds when installing via a custom OTA updater app. On my Pixel Tablet, the installation time for the update_engine DOWNLOADING phase decreased from 32:05 to 9:41. Note that this has absolutely no effect on the performance when sideloading from recovery mode because that does not use CoW.
When this new option is used, all dynamic partitions need to be …
=> Add support for changing VABC CoW compression algorithm

avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs, e2e/e2e.toml, e2e/src/config.rs, e2e/src/main.rs
AOSP has long supported CoW version 3, but it wasn't used by the stock OS on any Pixel devices until the new Pixel 9a.
CoW version 3 is fundamentally similar to version 2, though with differences in the main header and how the operation headers are stored. The compression is no longer done in fixed-size chunks equal to the block size. Instead, the payload specifies a "compression factor", which is the maximum chunk size to pass to the compressor. The actual chunk size is the largest power of 2 <= the compression factor and the remaining input size. Additionally, for version 3, the payload stores an additional `estimate_op_count_max` field containing the number of CoW operations.
While working on support for version 3, a few bugs in the version 2 estimation logic were found and fixed:
* …
=> payload: Add support for CoW version 3

avbroot/src/cli/ota.rs, avbroot/src/format/payload.rs, e2e/e2e.toml
No known device uses this, but it's very useful for testing that our overhead calculation is identical to AOSP's. A few more bugs were found in our overhead calculation logic:
* The `CowHeaderV3` size was missing the original `CowHeader` (v2) fields that are supposed to be included due to inheritance in the C++ class.
* The additional 1% overhead was incorrectly calculated against the initial CoW estimate before static overhead for CoW headers was added.
* The V3 `num_ops` estimation did not set a minimum of 25 to match `delta_generator`.
* The V2 `size` estimation did not take into account that a cluster of CoW operations cannot be truncated. It must be a multiple of cluster_ops (200 for avbroot).
With these fixes, the CoW estimation when compression is disabled matches AOSP exactly. …
=> payload: Add support for uncompressed CoW and fix more estimation bugs

avbroot/src/format/payload.rs, e2e/e2e.toml
No known device uses this functionality, but AOSP supports it, so we should too.
=> payload: Add support for custom CoW compression levels

e2e/e2e.toml, e2e/src/main.rs
It was hardcoded to set the CoW version to v2 in the payload manifest. This commit also updates the `pixel_v2` profile to disable VABC so that scenario gets tested. The `pixel_v3` profile now uses CoW v2 with gz.
=> e2e: Fix incorrect metadata when generating a non-CoW-V2 payload

avbroot/src/patch/boot.rs
There are no breaking changes.
=> Bump Magisk version upper bound to 29100

avbroot/src/format/ota.rs, e2e/e2e.toml
Our previous limit was 15 bytes for the `<offset>:<size>` placeholder, matching AOSP's `ota_utils.py`. Since the size of `metadata.pb` is almost always 4 digits, this leaves 10 digits for the offset, which isn't enough for large OTAs. AOSP never actually hits the limit because it puts `metadata` and `metadata.pb` at the beginning of the output zip file. We put the files at the end of the zip since we do streaming writes.
Fixes: #451
=> ota: Reserve 16 bytes for OTA metadata property files

avbroot/src/patch/boot.rs
There are no breaking changes.
=> Bump Magisk version upper bound to 30100

README.extra.md, avbroot/src/cli/avb.rs, avbroot/src/format/avb.rs, avbroot/src/format/hashtree.rs, avbroot/src/patch/system.rs
Previously, we automatically promoted SHA-1 to SHA-256 because SHA-1 is insecure, but there are devices that don't support SHA-256. It's safer to just keep using the original hash algorithm.
=> Allow using SHA-1 as AVB hash algorithm

avbroot/src/patch/boot.rs
There are no breaking changes.
=> Bump Magisk version upper bound to 30300

avbroot/src/cli/sparse.rs, avbroot/src/format/sparse.rs
`CHUNK_TYPE_RAW` is the only chunk type that's guaranteed to not overflow a u32 when its number of blocks is multiplied by the block size. `CHUNK_TYPE_FILL` and `CHUNK_TYPE_DONT_CARE` require a u64.
Issue: #472
=> sparse: Fix u32 overflow when unpacking files with large holes

Cargo.lock, avbroot/Cargo.toml, avbroot/src/cli/avb.rs, avbroot/src/cli/cpio.rs, avbroot/src/cli/lp.rs, avbroot/src/cli/ota.rs, avbroot/src/cli/payload.rs, avbroot/src/patch/boot.rs, avbroot/src/util.rs, e2e/src/main.rs
There is not much benefit for our use case to have kernel-level openat-style sandboxing of paths. We already check all untrusted paths for safety and the sandboxing prevented the use of symlinks that point outside of the parent directory of specified paths.
This commit also moves the path safety checks to the `util` module to avoid having multiple implementations spread out everywhere.
=> Remove cap-std and cap-tempfile dependencies

README.extra.md, avbroot/src/cli/avb.rs, avbroot/src/cli/ota.rs
This removes the need for the user to explicitly specify a public key to verify against.
Issue: #482
=> cli/avb: verify-device: Use bootloader's reported key digest by default

.github/workflows/ci.yml
Prior to Rust 1.89, these tests were just skipped when cross-compiling. Now, they are actually compiled and ran. Unfortunately, doctests don't use the normal `RUSTFLAGS` environment variable, so we also need to set `RUSTDOCFLAGS` or else the resulting dynamically linked executable will fail to run on a non-Android host.
Upstream change: https://github.com/rust-lang/cargo/pull/15462
=> ci.yml: Set RUSTDOCFLAGS to statically link doctests

avbroot/src/cli/sparse.rs, avbroot/src/format/ota.rs, avbroot/src/format/sparse.rs, avbroot/src/stream.rs
This will not make a meaningful performance difference for our use case, but does not make things any more complex either.
=> Use seek_relative where possible

avbroot/src/cli/ota.rs, avbroot/src/cli/payload.rs
This was overlooked during the initial implementation. Payload images using VABC, but without CoW size estimates, are unflashable outside of recovery.
=> cli/payload: Compute CoW size estimates during packing

avbroot/src/cli/avb.rs, avbroot/src/cli/boot.rs, avbroot/src/cli/cpio.rs, avbroot/src/cli/lp.rs, avbroot/src/cli/payload.rs
This is useful if the file format metadata is the only thing that the user needs.
=> cli: Allow skipping unpacking of images

avbroot/src/patch/boot.rs
There are no breaking changes.
=> Bump Magisk version upper bound to 30500
